//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BibliotecaEntities : DbContext
    {
        public BibliotecaEntities()
            : base("name=BibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<Domain> Domains { get; set; }
        public DbSet<Lend> Lends { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Publisher> Publishers { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Schimb> Schimbs { get; set; }
        public DbSet<booksView> booksViews { get; set; }
        public DbSet<raport_view> raport_view { get; set; }
        public DbSet<raport_view1> raport_view1 { get; set; }
    
        public virtual ObjectResult<afiseaza_carti_imprumutate_Result> afiseaza_carti_imprumutate(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<afiseaza_carti_imprumutate_Result>("afiseaza_carti_imprumutate", idParameter);
        }
    
        public virtual ObjectResult<afiseaza_carti_imprumutate_autor_Result> afiseaza_carti_imprumutate_autor(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<afiseaza_carti_imprumutate_autor_Result>("afiseaza_carti_imprumutate_autor", idParameter);
        }
    
        public virtual ObjectResult<afiseaza_carti_imprumutate_domeniu_Result> afiseaza_carti_imprumutate_domeniu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<afiseaza_carti_imprumutate_domeniu_Result>("afiseaza_carti_imprumutate_domeniu", idParameter);
        }
    
        public virtual ObjectResult<afiseaza_carti_imprumutate_editura_Result> afiseaza_carti_imprumutate_editura(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<afiseaza_carti_imprumutate_editura_Result>("afiseaza_carti_imprumutate_editura", idParameter);
        }
    
        public virtual ObjectResult<afiseaza_carti_imprumutate_titlu_Result> afiseaza_carti_imprumutate_titlu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<afiseaza_carti_imprumutate_titlu_Result>("afiseaza_carti_imprumutate_titlu", idParameter);
        }
    
        public virtual ObjectResult<cauta_dupa_autor_Result> cauta_dupa_autor(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cauta_dupa_autor_Result>("cauta_dupa_autor", nameParameter);
        }
    
        public virtual ObjectResult<cauta_dupa_domeniu_Result> cauta_dupa_domeniu(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cauta_dupa_domeniu_Result>("cauta_dupa_domeniu", nameParameter);
        }
    
        public virtual ObjectResult<cauta_dupa_editura_Result> cauta_dupa_editura(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cauta_dupa_editura_Result>("cauta_dupa_editura", nameParameter);
        }
    
        public virtual ObjectResult<cauta_dupa_titlu_Result> cauta_dupa_titlu(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cauta_dupa_titlu_Result>("cauta_dupa_titlu", nameParameter);
        }
    
        public virtual ObjectResult<return_card_Result> return_card(Nullable<int> id_membru)
        {
            var id_membruParameter = id_membru.HasValue ?
                new ObjectParameter("id_membru", id_membru) :
                new ObjectParameter("id_membru", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<return_card_Result>("return_card", id_membruParameter);
        }
    }
}
