
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BibliotecaN
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    public Book()
    {

        this.Lends = new HashSet<Lend>();

    }


    public int ID { get; set; }

    public string Titlu { get; set; }

    public Nullable<int> Autor { get; set; }

    public string ISBN { get; set; }

    public int Domeniu { get; set; }

    public Nullable<int> Editura { get; set; }

    public string Descriere { get; set; }

    public int Exemplare { get; set; }

    public string Imagine { get; set; }



    public virtual Author Author { get; set; }

    public virtual Domain Domain { get; set; }

    public virtual Publisher Publisher { get; set; }

    public virtual ICollection<Lend> Lends { get; set; }

}

}
