//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaN
{
    using System;
    using System.Collections.Generic;
    
    public partial class booksView
    {
        public int ID { get; set; }
        public string Titlu { get; set; }
        public string Autor { get; set; }
        public string ISBN { get; set; }
        public string Domeniu { get; set; }
        public string Editura { get; set; }
    }
}
