
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BibliotecaN
{

using System;
    using System.Collections.Generic;
    
public partial class Lend
{

    public int ID { get; set; }

    public int Book_ID { get; set; }

    public int Person_ID { get; set; }

    public System.DateTime Data_Imprumut { get; set; }

    public System.DateTime Data_Retur { get; set; }

    public Nullable<int> Stare_Imprumut { get; set; }



    public virtual Book Book { get; set; }

    public virtual Person Person { get; set; }

}

}
