//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schimb
    {
        public int ID { get; set; }
        public int ID_Solicitant { get; set; }
        public int ID_Destinatar { get; set; }
        public int ID_CARTE { get; set; }
        public int Accept_destinatar { get; set; }
    }
}
